files:
  - source: /src/assets/languages/fr.json
    translation: /src/assets/languages/%two_letters_code%.%file_extension%
  - source: /src/assets/ChangelogData.json
    translation: /src/assets/ChangelogData_%two_letters_code%.%file_extension%
